# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_everywhere', '0002_urlmetadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlmetadata',
            name='img',
        ),
        migrations.AddField(
            model_name='urlmetadata',
            name='img_link',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
