# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links_everywhere', '0004_auto_20160313_0501'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usermetadata',
            new_name='URLMetaData',
        ),
    ]
